### ISSUE TITLE
Выглядит как константа, мб вынести из метода хотя бы?

### ISSUE THREAD

**Issue by degoz16** [kpechenenko/weather-reciever#2]
https://github.com/kpechenenko/custom-weather-reciever/blob/60a246d277b3bf1c7707139e4bfc402f590660f6/src/main/java/ru/kpechenenko/weather_receiver/WeatherParser.java#L27

**Comment by ayakovlev18214** [comment]
Да и path вроде не abs :)

**Comment by kpechenenko** [comment]
Вынесено.
